
[package]
name = "pms-service-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
description = "Generated TeaQL service crate for pms-service"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-stream = "0.3"
futures-util = "0.3"
teaql-core = "5.0.3"
teaql-macros = "5.0.3"
teaql-runtime = "5.0.3"
teaql-sql = "5.0.3"
teaql-data-service = "5.0.3"
teaql-provider-sqlite = "5.0.3"
rusqlite = { version = "0.40", features = ["bundled", "chrono", "column_decltype"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
