[package]
name = "pms-service-core"
version = "0.1.0"
edition = "2021"
description = "Generated TeaQL service crate for pms-service"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
teaql-core = "4.2.2"
teaql-macros = "4.2.2"
teaql-runtime = "4.2.2"
teaql-sql = "4.2.2"
teaql-data-service = "4.2.2"
teaql-tool-core = "1.0.0"
teaql-provider-sqlite = "4.2.2"
rusqlite = { version = "0.40", features = ["bundled", "chrono", "column_decltype"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
